### ISSUE TITLE
Unable to run locally with Docker

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/mapping-viz-functions#11]
Following the Readme commands to run this repo locally with Docker results in the following error: `Worker was unable to load function subjects: 'Error: Cannot find module 'pg'`.

**Comment by srallen** [comment]
I see the same error. I think the possible issue is that there's a `yarn.lock` and a `package-lock.json` for the repository. It's possible these are conflicting. If yarn is being used, then the `yarn.lock` file should be definitive and `package-lock.json` removed.

It's also worth upgrading the postgres version and node version declared in the dockerfile, though, I doubt the pg and node version has anything to do with the error we're seeing. I believe the databases on Azure are version 11, though, @zwolf can confirm.

**Comment by zwolf** [comment]
Confirmed, recently migrated from 9.5. The above is a good idea to ensure compatibility through dumps/restores.

**Comment by goplayoutside3** [comment]
Removing the `package-lock.json` from the dockerfile and repo did not resolve the error, but running `yarn install` in the command line prior to `docker-compose run --rm app yarn start` did remove the error. I don't think I know enough about docker, but that seems a bit counterintuitive since the dockerfile already includes `RUN yarn install`.

Is that expected? If so, I can update the Readme and node version.

**Comment by eatyourgreens** [comment]
The docker compose file is set up to mount your local working directory to `/src` in the container. If you’ve got a local `node_modules` directory, that’ll be mounted to `/src/node_modules`, overwriting the yarn install.

**Comment by eatyourgreens** [comment]
You could try adding a list of files to ignore. Here’s an example from PFE. https://github.com/zooniverse/Panoptes-Front-End/blob/master/.dockerignore

That should, at least, tell Docker to ignore `node_modules` when it’s running `ADD`. 

EDIT: this seems to be a good guide to `.dockerignore`, and what to watch out for when copying or adding local files to an image. https://medium.com/hackernoon/do-not-ignore-dockerignore-47f5fb67b448#.ap1a8tfyc

**Comment by goplayoutside3** [comment]
Good to know @eatyourgreens! I'll add a `.gitignore` file in PR #13.
